# Site settings
title: Freedom Hunter
header-img: "img/dark_yellow.png"
tagline: "zluckyH"  
description: "一个产品经理，负责过数据产品、AI产品，擅长数据分析、产品设计、项目管理，利用AI开发了一个聊天工具，一个英语学习工具，一个音频转录工具，持续学习中！"  
baseurl: ""
url: "https://zluckyhou.github.io"

# About/contact
owner: 
  name: " zluckyH"
  email: zluckyhou@163.com
  bio: "Stay Hungry, Stay Foolish! "

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: 
twitter_username: John43497285
github_username: zluckyhou
facebook_username: 
#weibo_username:  
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "zluckyH"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white


# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

# url: "https://zluckyhou.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-paginate
